[build]
functions = "functions"
command = "yarn run build"
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Credentials = "true"
Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
Access-Control-Allow-Methods = "GET"
Access-Control-Allow-Origin = "*"
Access-Control-Max-Age = "3600"